import Foundation
import WebRTC

/// The orchestrator that ties transports, pairing, WebRTC fan-out, heartbeat,
/// and the sensor send loop together — a direct Swift port of
/// `client/src/phone.ts`'s `startPhoneClient()` (connect → pair → fan-out,
/// Task 1) and `attemptReconnect()` (the reconnect loop, Task 2).
///
/// D-04 is enforced here: WebTransport is attempted first every time,
/// WebSocket is the fallback — never a WS-only happy path. Because this
/// manager is transport-agnostic (it drives whichever `SignalingTransport`
/// connected, via `ActiveTransportDispatcher` below), a failed WebTransport
/// spike (Plan 05) degrades here purely at runtime with zero code change.
///
/// Implemented as an ordinary (implicitly `@MainActor`, per this project's
/// `SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor` build setting)
/// `final class` rather than a Swift `actor` — this keeps it consistent
/// with every other controller in this codebase (`PeerConnectionManager`,
/// `WebSocketSignaling`, `WebTransportSignaling`, none of which are actors)
/// and avoids cross-actor friction with `PeerConnectionManager`, which is
/// an `NSObject`-based `RTCPeerConnectionDelegate`/`RTCDataChannelDelegate`
/// (Objective-C delegate protocols do not mix well with Swift actors). The
/// CoreMotion orientation callback fires on a dedicated background queue
/// (`CoreMotionSource`'s own doc comment: "NOT the main actor") — this
/// manager explicitly hops to `@MainActor` itself before touching any
/// shared state (`startSensorLoopIfNeeded()`), exactly as that doc comment
/// instructs callers to do.
final class TransportManager {

    // MARK: - Connection state (introspection / future UI wiring — Plan 08)

    enum ConnectionState: Equatable {
        case idle
        case connecting
        case paired
        case reconnecting
        case ended
        case error(String)
    }

    private(set) var state: ConnectionState = .idle

    // MARK: - Identity + session state (mirrors phone.ts's module-scope vars)

    /// Generated once, reused across every reconnect (Shared Pattern:
    /// `myId` persistence) — never regenerated by either the WT or WS path.
    let myId: String

    private(set) var mySlot: Int?
    private(set) var roomCode: String?
    private(set) var myUsername: String?
    private(set) var peerIds: [String] = []
    private(set) var reconnectToken: String?

    /// Mirrors `phone.ts`'s top-level `registered` flag — guards
    /// `sendPhoneState`-equivalent sends and the self-heal reopen path.
    /// Kept in sync with `peerFanOut.registered`.
    private(set) var registered = false

    private(set) var activeTransport: SignalingTransport?

    /// Snapshot of currently-open WebRTC data channels — exposed read-only
    /// so `SessionViewModel` (Plan 08) can poll it at a throttled UI rate
    /// (Pitfall 3) without reaching into the private `peerFanOut`. Never
    /// read from the 60Hz sensor send path itself.
    var openChannelCount: Int { peerFanOut.openDataChannels.count }

    /// `true` while `attemptReconnect()` owns the connection lifecycle —
    /// mirrors `phone.ts`'s `_reconnecting` guard, which suppresses a
    /// second concurrent reconnect loop from `onClosed` firing again mid-loop.
    /// Set by Task 2's `attemptReconnect()` implementation.
    private(set) var isReconnecting = false

    private var host: String = ""

    // MARK: - Collaborators

    /// The single `SignalingTransport` handed to `PeerConnectionManager`
    /// and `HeartbeatTimer` (Shared Pattern: envelope dispatch) — its
    /// `current` pointer is swapped to whichever concrete transport is
    /// active, so every downstream sender always rides the live transport,
    /// even across a reconnect that swaps WT↔WS underneath it.
    private let dispatcher: ActiveTransportDispatcher
    private let peerFanOut: PeerFanOut
    private let heartbeatTimer: HeartbeatTimer
    private let motionSource: CoreMotionSource
    private let clock: TransportManagerClock

    private let makeWebTransport: (String, String) -> SignalingTransport
    private let makeWebSocket: (String, String) -> SignalingTransport

    /// 10s timeout on the WebSocket-fallback initial connect (phone.ts:412-429).
    private let wsConnectTimeout: TimeInterval

    // MARK: - Reconnect shape (attemptReconnect(), phone.ts:507-631 — injectable for tests)

    private let reconnectInitialDelay: TimeInterval
    private let reconnectBetweenDelay: TimeInterval
    private let maxReconnectAttempts: Int
    private let wtReconnectTimeout: TimeInterval
    private let wsReconnectTimeout: TimeInterval

    // MARK: - Sensor encode/send loop state (D-09: orientation only)

    private var sensorLoopStarted = false
    private var seq: Int = 0
    private var sessionStart: Double = 0
    private var encodeBuffer: Data = SensorPacketEncoder.makeBuffer()

    init(
        myId: String = UUID().uuidString,
        makeWebTransport: @escaping (String, String) -> SignalingTransport = { host, myId in
            WebTransportSignaling(host: host, myId: myId)
        },
        makeWebSocket: @escaping (String, String) -> SignalingTransport = { host, myId in
            WebSocketSignaling(host: host, myId: myId)
        },
        makePeerFanOut: (SignalingTransport, String) -> PeerFanOut = { transport, myId in
            PeerConnectionManager(transport: transport, myId: myId)
        },
        motionSource: CoreMotionSource = CoreMotionSource(),
        heartbeatScheduler: HeartbeatScheduler = TimerHeartbeatScheduler(),
        heartbeatInterval: TimeInterval = 5.0,
        clock: TransportManagerClock = SystemTransportManagerClock(),
        wsConnectTimeout: TimeInterval = 10.0,
        reconnectInitialDelay: TimeInterval = 3.0,
        reconnectBetweenDelay: TimeInterval = 10.0,
        maxReconnectAttempts: Int = 13,
        wtReconnectTimeout: TimeInterval = 5.0,
        wsReconnectTimeout: TimeInterval = 10.0
    ) {
        self.myId = myId
        self.makeWebTransport = makeWebTransport
        self.makeWebSocket = makeWebSocket
        self.motionSource = motionSource
        self.clock = clock
        self.wsConnectTimeout = wsConnectTimeout
        self.reconnectInitialDelay = reconnectInitialDelay
        self.reconnectBetweenDelay = reconnectBetweenDelay
        self.maxReconnectAttempts = maxReconnectAttempts
        self.wtReconnectTimeout = wtReconnectTimeout
        self.wsReconnectTimeout = wsReconnectTimeout

        // Local (non-`self`) captures only, so these closures are safe to
        // build before Swift's two-phase class init completes.
        let dispatcher = ActiveTransportDispatcher()
        self.dispatcher = dispatcher
        self.peerFanOut = makePeerFanOut(dispatcher, myId)
        self.heartbeatTimer = HeartbeatTimer(
            interval: heartbeatInterval,
            scheduler: heartbeatScheduler,
            myId: { myId },
            send: { envelope in dispatcher.send(envelope) }
        )
    }

    // MARK: - Initial connect (startPhoneClient(), phone.ts:371-486)

    /// Attempts WebTransport first; on failure connects WebSocket (D-04
    /// ordering). On `pair-ack`, extracts session fields, fans out one data
    /// channel per peer, starts the heartbeat, and starts the CoreMotion
    /// orientation-only sensor loop (D-09).
    func start(token: String, host: String) async {
        self.host = host
        state = .connecting

        let transport: SignalingTransport
        if let wt = await tryInitialWebTransport(host: host) {
            transport = wt
        } else {
            guard let ws = await tryInitialWebSocket(host: host) else {
                state = .error("Cannot reach the server. Make sure this device trusts the TLS certificate.")
                return
            }
            transport = ws
        }
        activate(transport)

        let pairEnvelope = SignalingEnvelope(
            type: SignalingEnvelope.SignalingType.pair,
            from: myId,
            to: "",
            payload: ["token": AnyCodable(token)]
        )
        let pairResp: SignalingEnvelope
        do {
            pairResp = try await transport.request(pairEnvelope)
        } catch let error as WebSocketSignalingError {
            // The WebSocket path rejects a pending `pair` continuation by
            // THROWING `WebSocketSignalingError.requestFailed(reason:)` on a
            // structured `pair-error` response (unlike WebTransport, which
            // returns `pair-error` as an ordinary envelope handled by the
            // `pairResp.type != .pairAck` branch below) — synthesize the
            // equivalent envelope so the server-provided reason still
            // reaches the same extraction logic, mirroring phone.ts's
            // `.catch(reason => ({ type: 'pair-error', payload: { reason } }))`
            // (phone.ts:452-454). `unsupportedRequestType` never fires for a
            // `.pair` envelope (`request(_:)` supports it), but is handled
            // defensively with the generic message rather than force-unwrapped.
            switch error {
            case .requestFailed(let reason):
                pairResp = SignalingEnvelope(
                    type: SignalingEnvelope.SignalingType.pairError,
                    from: "", to: "",
                    payload: ["reason": AnyCodable(reason)]
                )
            case .unsupportedRequestType:
                state = .error("Server connection dropped during pairing.")
                return
            }
        } catch {
            state = .error("Server connection dropped during pairing.")
            return
        }

        guard pairResp.type == SignalingEnvelope.SignalingType.pairAck else {
            let reason = (pairResp.payload["reason"]?.value as? String)
                ?? "This pairing link is invalid or has expired."
            state = .error(reason)
            return
        }

        applyPairAck(pairResp)
    }

    /// Attempt 1: WebTransport. No explicit timeout on this specific call
    /// (unlike reconnect's 5s race) — mirrors `startPhoneClient()`'s bare
    /// `await transport.ready`. Returns `nil` on any failure so the caller
    /// falls through to WebSocket.
    private func tryInitialWebTransport(host: String) async -> SignalingTransport? {
        let candidate = makeWebTransport(host, myId)
        do {
            try await candidate.connect()
            return candidate
        } catch {
            return nil
        }
    }

    /// Attempt 2: WebSocket fallback, only reached if WT failed — 10s
    /// timeout (phone.ts:412-429).
    private func tryInitialWebSocket(host: String) async -> SignalingTransport? {
        let candidate = makeWebSocket(host, myId)
        do {
            try await withTransportTimeout(wsConnectTimeout, clock: clock) {
                try await candidate.connect()
            }
            return candidate
        } catch {
            return nil
        }
    }

    private func applyPairAck(_ envelope: SignalingEnvelope) {
        mySlot = envelope.slot
        roomCode = envelope.roomCode
        myUsername = envelope.payload["username"]?.value as? String
        reconnectToken = envelope.reconnectToken
        peerFanOut.iceServers = ICEConfig.iceServers(from: envelope.iceServers)

        let ids = (envelope.peers ?? []).compactMap { entry -> String? in
            (entry as? [String: Any])?["id"] as? String
        }
        peerIds = ids

        registered = true
        peerFanOut.registered = true
        state = .paired

        ids.forEach { peerFanOut.openChannel(toPeer: $0, isRecovery: false) }

        heartbeatTimer.start()
        startSensorLoopIfNeeded()
    }

    // MARK: - Transport activation + server-push routing

    /// Commits `transport` as the active transport: wires its push/close
    /// callbacks and repoints the shared dispatcher (Shared Pattern:
    /// envelope dispatch) so `PeerConnectionManager`/`HeartbeatTimer`
    /// immediately ride the new transport.
    private func activate(_ transport: SignalingTransport) {
        transport.onServerPush = { [weak self] envelope in self?.handleServerPush(envelope) }
        transport.onClosed = { [weak self] reason in self?.handleTransportClosed(reason: reason) }
        activeTransport = transport
        dispatcher.current = transport
    }

    /// Routes every unsolicited server envelope — mirrors `handleServerPush`
    /// (phone.ts:1113-1172). Calibration/ARKit-driven pushes (`player-ready`
    /// and friends) are out of scope for this phase (D-01/D-09) and are
    /// intentionally no-ops here.
    private func handleServerPush(_ envelope: SignalingEnvelope) {
        switch envelope.type {
        case SignalingEnvelope.SignalingType.answer:
            peerFanOut.applyRemoteAnswer(envelope, for: envelope.from)
        case SignalingEnvelope.SignalingType.iceCandidate:
            peerFanOut.addRemoteCandidate(envelope, for: envelope.from)
        case SignalingEnvelope.SignalingType.peerJoined:
            if let peer = envelope.payload["peer"]?.value as? [String: Any],
               let peerId = peer["id"] as? String {
                peerFanOut.openChannel(toPeer: peerId, isRecovery: false)
            }
        case SignalingEnvelope.SignalingType.peerLeft:
            if let peerId = envelope.payload["peer_id"]?.value as? String {
                peerFanOut.closePeer(peerId)
            }
        default:
            break // player-ready / session-ended / etc. — out of scope this phase.
        }
    }

    // MARK: - Reconnect trigger (full loop ported in Task 2, attemptReconnect(), phone.ts:507-631)

    /// Fires when the active transport closes — mirrors `onWtClose`/
    /// `ws.onclose`: clears connected state, stops the heartbeat, and
    /// kicks off `attemptReconnect()`. Suppressed while a reconnect is
    /// already in flight (mirrors `_reconnecting`).
    private func handleTransportClosed(reason: String) {
        guard !isReconnecting else { return }
        registered = false
        peerFanOut.registered = false
        heartbeatTimer.stop()
        activeTransport = nil
        dispatcher.current = nil
        Task { [weak self] in
            await self?.attemptReconnect()
        }
    }

    /// Direct port of `attemptReconnect()`: no `reconnectToken` ⇒ ended;
    /// otherwise a 3s initial delay, then up to `maxReconnectAttempts`
    /// attempts (default 13) with `reconnectBetweenDelay` (default 10s)
    /// between them. Each iteration tries WT first; `slot_not_held` skips
    /// the WS sub-attempt for that iteration (both transports would return
    /// the same result); only `slot_not_held`/`ws-closed`/`wt-net` are
    /// retryable — any other reason (or exhausting all attempts) is terminal.
    func attemptReconnect() async {
        guard let token = reconnectToken else {
            state = .ended
            return
        }

        isReconnecting = true
        state = .reconnecting
        await clock.sleep(reconnectInitialDelay)

        for attempt in 1...maxReconnectAttempts {
            let isLastAttempt = attempt == maxReconnectAttempts

            switch await tryWtReconnect(token: token) {
            case .joined(let transport, let response):
                completeReconnect(with: transport, response: response)
                return
            case .failed(let reason):
                if reason == "slot_not_held" {
                    if isLastAttempt { finishReconnectFailure(); return }
                    await clock.sleep(reconnectBetweenDelay)
                    continue
                }
                // Any other WT failure falls through to the WS sub-attempt.
            }

            switch await tryWsReconnect(token: token) {
            case .joined(let transport, let response):
                completeReconnect(with: transport, response: response)
                return
            case .failed(let reason):
                let retryable = reason == "slot_not_held" || reason == "ws-closed" || reason == "wt-net"
                if retryable, !isLastAttempt {
                    await clock.sleep(reconnectBetweenDelay)
                    continue
                }
                finishReconnectFailure()
                return
            }
        }

        finishReconnectFailure()
    }

    private enum ReconnectAttemptResult {
        case joined(SignalingTransport, SignalingEnvelope)
        case failed(reason: String)
    }

    /// Try 1 (per iteration): fresh WebTransport, 5s connect timeout,
    /// commit only on `join-ack` — mirrors `tryWtReconnect()`
    /// (phone.ts:334-368). WebTransport returns `join-error` as an ordinary
    /// envelope (not a thrown error), so its `reason` payload field is read
    /// directly.
    private func tryWtReconnect(token: String) async -> ReconnectAttemptResult {
        let candidate = makeWebTransport(host, myId)
        do {
            try await withTransportTimeout(wtReconnectTimeout, clock: clock) {
                try await candidate.connect()
            }
            let response = try await candidate.request(reconnectEnvelope(token: token))
            if response.type == SignalingEnvelope.SignalingType.joinAck {
                return .joined(candidate, response)
            }
            candidate.close()
            let reason = (response.payload["reason"]?.value as? String) ?? ""
            return .failed(reason: reason)
        } catch {
            candidate.close()
            return .failed(reason: "wt-net")
        }
    }

    /// Try 2 (per iteration, only if WT didn't join): fresh WebSocket, 10s
    /// connect timeout — mirrors the WS sub-path inside `attemptReconnect()`
    /// (phone.ts:548-581). Unlike WebTransport, `WebSocketSignaling.request(_:)`
    /// rejects a pending `reconnect` continuation by THROWING
    /// `WebSocketSignalingError.requestFailed(reason:)` on a structured
    /// `join-error` response — that thrown reason must be unwrapped here
    /// rather than collapsed into the always-retryable "ws-closed" bucket,
    /// or a genuine terminal join-error would incorrectly retry to the
    /// ceiling. A connect()-level failure (network/timeout) has no
    /// server-provided reason and is legitimately "ws-closed".
    private func tryWsReconnect(token: String) async -> ReconnectAttemptResult {
        let candidate = makeWebSocket(host, myId)
        do {
            try await withTransportTimeout(wsReconnectTimeout, clock: clock) {
                try await candidate.connect()
            }
        } catch {
            candidate.close()
            return .failed(reason: "ws-closed")
        }

        do {
            let response = try await candidate.request(reconnectEnvelope(token: token))
            if response.type == SignalingEnvelope.SignalingType.joinAck {
                return .joined(candidate, response)
            }
            candidate.close()
            let reason = (response.payload["reason"]?.value as? String) ?? ""
            return .failed(reason: reason)
        } catch let error as WebSocketSignalingError {
            candidate.close()
            switch error {
            case .requestFailed(let reason):
                return .failed(reason: reason)
            case .unsupportedRequestType:
                return .failed(reason: "ws-closed")
            }
        } catch {
            candidate.close()
            return .failed(reason: "ws-closed")
        }
    }

    private func reconnectEnvelope(token: String) -> SignalingEnvelope {
        SignalingEnvelope(
            type: SignalingEnvelope.SignalingType.reconnect,
            from: myId,
            to: "",
            payload: ["reconnect_token": AnyCodable(token)]
        )
    }

    /// On `join-ack` (from either transport): update token/ice servers,
    /// mark registered, restart heartbeat (idempotent), and reopen any
    /// peer whose data channel is closed/closing or whose pc is `failed`
    /// (phone.ts:584-607) — delegated to `PeerConnectionManager`'s own
    /// collect-then-reopen `reopenStaleChannels()`.
    private func completeReconnect(with transport: SignalingTransport, response: SignalingEnvelope) {
        activate(transport)
        if let newToken = response.reconnectToken { reconnectToken = newToken }
        if let ice = response.iceServers { peerFanOut.iceServers = ICEConfig.iceServers(from: ice) }

        registered = true
        peerFanOut.registered = true
        isReconnecting = false
        state = .paired

        peerFanOut.reopenStaleChannels()
        heartbeatTimer.start()
    }

    /// Terminal path: only `slot_not_held`/`ws-closed`/`wt-net` are
    /// retryable; anything else, or exhausting all attempts, clears the
    /// token, stops the heartbeat, and transitions to `.ended`
    /// (phone.ts:618-631).
    private func finishReconnectFailure() {
        isReconnecting = false
        reconnectToken = nil
        heartbeatTimer.stop()
        state = .ended
    }

    // MARK: - Sensor encode/send loop (D-09: orientation only, position/gesture/drift stay zero)

    /// Starts the CoreMotion-driven encode/send loop exactly once per
    /// session (not restarted on reconnect — mirrors the web client never
    /// re-attaching its `devicemotion` listener on reconnect either).
    /// `CoreMotionSource`'s callback fires on its own dedicated background
    /// queue (never the main actor); this explicitly hops back to
    /// `@MainActor` per that class's own doc-comment guidance before
    /// touching any shared state.
    private func startSensorLoopIfNeeded() {
        guard !sensorLoopStarted else { return }
        sensorLoopStarted = true
        sessionStart = Date().timeIntervalSince1970 * 1000

        motionSource.onOrientation = { [weak self] quaternion in
            Task { @MainActor in
                self?.handleOrientation(quaternion)
            }
        }
        motionSource.start()
    }

    /// One CoreMotion sample → one encoded `SensorPacket`, broadcast to
    /// every currently open data channel. Only `qw`/`qx`/`qy`/`qz` carry
    /// real data — `dx`/`dy`/`dz`/`px`/`py`/`pz`/`driftConfidence` are
    /// NEVER set here and default to zero (D-01/D-09; real position data
    /// lands in Phase 06.3's ARKit integration).
    private func handleOrientation(_ quaternion: CoreMotionSource.Quaternion) {
        let now = Date().timeIntervalSince1970 * 1000
        let packet = SensorPacket(
            seq: seq,
            timestamp: now - sessionStart,
            qw: quaternion.qw,
            qx: quaternion.qx,
            qy: quaternion.qy,
            qz: quaternion.qz
        )
        seq += 1

        SensorPacketEncoder.encodePacket(packet, into: &encodeBuffer)
        // Copy before send — `encodeBuffer` is reused (overwritten) on the
        // very next tick (Pitfall 5, no per-tick GC pressure at 60Hz).
        let bytes = Data(encodeBuffer)
        let buffer = RTCDataBuffer(data: bytes, isBinary: true)
        for channel in peerFanOut.openDataChannels {
            channel.sendData(buffer)
        }
    }
}

// MARK: - ActiveTransportDispatcher (Shared Pattern: envelope dispatch)

/// A `SignalingTransport` conformance whose `current` pointer is swapped by
/// `TransportManager` to whichever concrete transport (WT or WS) is
/// currently active. Handed to `PeerConnectionManager` and `HeartbeatTimer`
/// so every signaling send they issue always rides the LIVE transport, even
/// across a reconnect that replaces the underlying transport instance —
/// mirrors `phone.ts`'s `signalSend()`, which reads the live `useWt`/
/// `transport`/`ws` module state on every call rather than capturing a
/// snapshot (PATTERNS.md "Shared Patterns → Envelope dispatch").
final class ActiveTransportDispatcher: SignalingTransport {
    var current: SignalingTransport?

    var onServerPush: ((SignalingEnvelope) -> Void)?
    var onClosed: ((String) -> Void)?
    var isWebTransport: Bool { current?.isWebTransport ?? false }

    func connect() async throws { try await current?.connect() }

    func send(_ envelope: SignalingEnvelope) { current?.send(envelope) }

    func request(_ envelope: SignalingEnvelope) async throws -> SignalingEnvelope {
        guard let current else { throw TransportManagerError.noActiveTransport }
        return try await current.request(envelope)
    }

    func close() { current?.close() }
}

enum TransportManagerError: Error {
    case noActiveTransport
}

// MARK: - PeerFanOut (testable seam over PeerConnectionManager)

/// The subset of `PeerConnectionManager`'s surface `TransportManager`
/// depends on, extracted as a protocol purely for dependency injection
/// (`PeerConnectionManagerTests.swift` already proves `PeerConnectionManager`
/// itself is fully offline-testable; this lets `TransportManagerTests`
/// inject a lightweight spy instead of constructing real WebRTC objects for
/// every reconnect/fan-out assertion). Declared here — not in
/// `WebRTC/PeerConnectionManager.swift` — to keep this plan's edits scoped;
/// `PeerConnectionManager` conforms via the retroactive extension below.
protocol PeerFanOut: AnyObject {
    var iceServers: [RTCIceServer] { get set }
    var registered: Bool { get set }
    var peerCount: Int { get }
    var openDataChannels: [RTCDataChannel] { get }

    func openChannel(toPeer peerId: String, isRecovery: Bool)
    func closePeer(_ peerId: String)
    /// Reopens any peer whose data channel is closed/closing or whose peer
    /// connection state is `failed` — the collect-then-reopen pattern from
    /// `attemptReconnect()` (phone.ts:594-604). Added in Task 2 for the
    /// reconnect loop's post-`join-ack` self-heal; already implemented on
    /// `PeerConnectionManager` since Plan 06.
    func reopenStaleChannels()
    func applyRemoteAnswer(_ envelope: SignalingEnvelope, for peerId: String)
    func addRemoteCandidate(_ envelope: SignalingEnvelope, for peerId: String)
}

extension PeerConnectionManager: PeerFanOut {}

// MARK: - TransportManagerClock (injectable delay — fast/virtual clock in tests)

/// Abstraction over "wait `seconds`" — exists so `TransportManager`'s
/// reconnect loop never calls `Task.sleep` directly, letting tests inject a
/// clock that returns immediately (no real 3s/10s waits) while production
/// code uses `SystemTransportManagerClock`.
protocol TransportManagerClock {
    func sleep(_ seconds: TimeInterval) async
}

final class SystemTransportManagerClock: TransportManagerClock {
    func sleep(_ seconds: TimeInterval) async {
        try? await Task.sleep(nanoseconds: UInt64(max(0, seconds) * 1_000_000_000))
    }
}

// MARK: - Timeout helper (used for the WS-initial connect and Task 2's reconnect sub-attempts)

private struct TransportTimeoutError: Error {}

/// Races `operation` against a `seconds`-long timeout sourced from the
/// injected clock (so tests never wait on a real timer) — mirrors
/// `Promise.race([operation, timeout])` in `phone.ts`'s WS-connect and WT-
/// reconnect timeout guards.
private func withTransportTimeout<T: Sendable>(
    _ seconds: TimeInterval,
    clock: TransportManagerClock,
    operation: @escaping @Sendable () async throws -> T
) async throws -> T {
    try await withThrowingTaskGroup(of: T.self) { group in
        group.addTask { try await operation() }
        group.addTask {
            await clock.sleep(seconds)
            throw TransportTimeoutError()
        }
        guard let result = try await group.next() else {
            throw TransportTimeoutError()
        }
        group.cancelAll()
        return result
    }
}
